### PR TITLE
Upgrade cloudstate-java-support to 0.5.0

### PR DESCRIPTION
**Pull request by vkorenev**
Upgrade cloudstate-java-support to 0.5.0.

It fails to compile with an internal exception in Kotlin compiler. The message looks similar to https://youtrack.jetbrains.com/issue/KT-38157

### CODE REVIEW

**Comment by sleipnir** [comment]
Hii @vkorenev  the same with version 0.4.7?

**Comment by sleipnir** [comment]
I suspect the cause of the problem is the resolvedMethods method of the trait ResolvedEntityFactory

**Comment by vkorenev** [comment]
@sleipnir no, 0.4.7 does not seem to trigger this error. There are just "normal" compilation errors because of changes in `cloudstate-java-support`.

**Comment by sleipnir** [comment]
Ok. what do you think about moving to 0.4.7 while investigating 0.5.0?

**Comment by sleipnir** [comment]
I migrated to 0.4.7

**Comment by sleipnir** [comment]
@vkorenev despite having migrated to version 0.4.7 it will be necessary to migrate to version 0.5.0 at some point. So I opened an issue to address this issue

**Pull request closed without merging**
