### PR TITLE
First interaction of Kotlin language support

### PR DESCRIPTION
**Pull request by sleipnir**
Support for the EventSourced protocol.
All TCK tests pass.
This being approved, I follow with the PR in the documentation!
Then I add the CRDT support.

### CODE REVIEW

**Comment by sleipnir** [comment]
This is TCK setup:
```
cloudstate-tck.combinations = [{
   name = "Akka + Kotlin"
   tck {
     hostname = "0.0.0.0"
     port = 8090
   }
   proxy {
     hostname = "127.0.0.1"
     port = 9000
     directory = ${user.dir}
     command = ["java","-Xmx512M", "-Xms128M", "-Dconfig.resource=in-memory.conf", "-Dcloudstate.proxy.dev-mode-enabled=true", "-jar", "proxy/core/target/scala-2.12/akka-proxy.jar"]
     env-vars {
       USER_FUNCTION_PORT = "8090"
     }
   }

   frontend {
     hostname = "127.0.0.1"
     port = 8088
     directory = ${user.dir}
     command = ["docker", "run", "--rm", "-p", "127.0.0.1:8088:8080", "sleipnir/shopping-cart:latest"]
     env-vars {
       HOST = "127.0.0.1"
       PORT = "8088"
     }
   }
}]
```

**Comment by ihostage** [comment]
Thank you, @sleipnir! 
Some ideas:
1. Use Gradle (Kotlin DSL) for the Kotlin Support repository.
2. Need to remove all `proto` files and all generated files from this repository. And use a protocol artifact (https://github.com/cloudstateio/cloudstate/pull/153) for generating a code on pre-compile time.

**Comment by sleipnir** [comment]
Hi @ihostage Thanks for the comments.
1. Yes, I'm likely to change that. Today it is like that for compatibility with cloudstate cli that doesn't know, yet, to deal with gradle.
2. In fact, protos files are totally unnecessary for this implementation, since at the level of the cloudstate protocol the heavy work is done by the java-support library. They are in the project because of my first implementation approach and I will remove them soon.

Is it okay for you to keep it that way for now?

**Comment by ihostage** [comment]
> Is it okay for you to keep it that way for now?

Yes, of course. We can remove it later.

**Comment by sleipnir** [comment]
@ihostage I had to add the proto files for testing purposes only.

**Comment by viktorklang** [comment]
@sleipnir Given the size of this PR I thought it best to just merge it and then have incremental reviewing by those who know Kotlin :)

**Comment by sleipnir** [comment]
Thanks @viktorklang

**Pull request merged**
